### ISSUE TITLE
[Bug]: GitHubから直接ファイルをダウンロードして試してみたが、エラーを吐いてうまく機能してくれない

### ISSUE THREAD

**Issue by yujean9191** [yakisova41/return-youtube-comment-username#101]
### Browser

Brave

### Version

Brave  1.64.113 Chromium: 123.0.6312.86（Official Build） （64 ビット）

### YouTube Client Version

youtube.player.web_20240326_01_RC00

### Release Type

Chrome Extension

### The URL where the problem occurred

https://www.youtube.com/watch?v=-aNoD17Tcg8

### What is the problem?

![image](https://github.com/yakisova41/return-youtube-comment-username/assets/165744084/3a630587-5be0-4303-8efd-9a357733b58a)
`import { handleYtAppendContinuationItemsAction } from "./handlers/handleYtAppendContinuationItemsAction";`

待ちきれなくて直接Githubからファイルを入手してパッケージ化されていない拡張機能を取り込むという機能で取り込んでみたのですが、以上のようにエラーを吐いていて機能しません。

**Comment by yakisova41** [comment]
ソースコードをそのまま読み込んでませんか？
[release](https://github.com/yakisova41/return-youtube-comment-username/releases/tag/v0.5.0)のchrome.zipを解答してぶちこめば多分読み込めます。

**Comment by yujean9191** [comment]
ありがとうございます！
無事、拡張機能が機能しました
マジで神
