### ISSUE TITLE
[Bug]:  it doesn't work.

### ISSUE THREAD

**Issue by wiful10** [yakisova41/return-youtube-comment-username#114]
### Browser

chrome 125.0.6422.77

### Release Type

Userscript

### Userscript manager

Tampermonkey 5.1.1

### The URL where the problem occurred

https://www.youtube.com/watch?v=djV11Xbc914

### What scripts or extensions do you use with it?

adguard chrome

### Screenshot

![캡처](https://github.com/yakisova41/return-youtube-comment-username/assets/102317996/5e2b1580-9828-467b-bb49-abd0bfc4c619)

### What is the problem?

Some accounts work fine, some don't.

**Comment by woofingcough** [comment]
The same goes for me.

**Comment by yakisova41** [comment]
Would you paste the screenshot of error log in devtools.
I cannot fix it without error log and debug info.
@wiful10 

### How to open the devtools.
- Press F12 with page opening.
- You can open it such as this one.
![スクリーンショット 2024-06-07 212402](https://github.com/yakisova41/return-youtube-comment-username/assets/75610521/a2122c11-9163-4a9c-8a43-178929aa81c3)

**Comment by wiful10** [comment]
![1](https://github.com/yakisova41/return-youtube-comment-username/assets/102317996/ee693881-6e7b-4e69-8409-78d6b591830e)


This is a screenshot. Is it right to do this? 

※ The script works fine for other accounts, but the problem occurs only for this account. Also, creating a new brand account causes problems.

**Comment by wiful10** [comment]
![337690698-ed9cf6ac-ad55-4ffa-8fbb-58854cb7ac6c](https://github.com/yakisova41/return-youtube-comment-username/assets/102317996/6e181576-8765-46f3-9350-0dde61b82282)

I don't know if it's related, but I've seen logs like this in other similar scripts.

**Comment by yakisova41** [comment]
Maybe, Youtube has changed specification of themself again for some user.
It change is apply to all user gradually.
so I will fix this problem when its change applied to my account.

**Comment by wiful10** [comment]
OK. Thank you!

**Comment by wiful10** [comment]
Unfortunately, it still doesn't work. According to the logs, it seems like the script is running, but there's a strange situation where it isn't converting to the actual username.

**Comment by wiful10** [comment]
Suddenly today it works fine :) It looks like Google was testing something.
