### ISSUE TITLE
There is a 1 second delay on the YT handles before the names appear.

### ISSUE THREAD

**Issue by mrkrabs206** [yakisova41/return-youtube-comment-username#34]
Hi, there is a 1 second delay on the YT handles before the names appear or extension not working correctly at all. Please fix this,
We will thank you.

**Comment by yakisova41** [comment]
Thanks for the Issue.
I would like to ask a few questions.
- Are you using the latest version 0.2.3?
- In which videos or pages does the bug occur? Or does it occur on all pages?
- Do you use any other Youtube related extensions or userscripts in conjunction?
- Do you see any errors in the console (press F12)?

**Comment by mrkrabs206** [comment]
Yes
Everywhere, even when posting a comment or reply myself
Return YouTube Dislike, YouTube channel location, No YouTube Shorts and Youtube-shorts block
None, it was from other extensions

**Comment by lheydon** [comment]
I actually experience this too, although I just assumed it was just an inevitable reality of how the script worked rather than an issue per se.
