### ISSUE TITLE
Usernames returned in top level of notifications but not second level

### ISSUE THREAD

**Issue by lheydon** [yakisova41/return-youtube-comment-username#36]
Thanks for this script, it is a total godsend against a highly annoying change by YouTube!

One fault is that usernames are returned in the top level of the notifications box, but not at the second level. See attached screenshot.

![Return-You-Tube-Comment-Username-fault.png](https://i.ibb.co/JKD8D70/Return-You-Tube-Comment-Username-fault.png)

I'm using the Chrome extension version (your version **0.3.2**)

Chrome is version **114.0.5735.134** (Official Build) (64-bit)).

I am using a VPN, AdBlock and Privacy Badger.

I'm new to GitHub, so let me know if I need to provide other information.

Thanks in advance!

**Comment by lheydon** [comment]
> [Google Translated] Added a function to rewrite comments in the notification column

**_yakisova41_**, will that change also get pushed through in an update to the Chrome Extension?

**Comment by yakisova41** [comment]
Thanks for the issue.
We are about to submit the corrected version v0.3.3 to the web store for review, so it will be released in an hour or so at the latest.
I would appreciate it if you could let me know if it works after the update.

**Comment by lheydon** [comment]
> Thanks for the issue.
> We are about to submit the corrected version v0.3.3 to the web store for review, so it will be released in an hour or so at the latest.
> I would appreciate it if you could let me know if it works after the update.

Excellent, will do 👍

**Comment by lheydon** [comment]
**_yakisova41_**, have just upgraded to **0.3.3** but this does not resolve the issue.

**Comment by yakisova41** [comment]
Oops sorry!
I did not read the issue carefully😖😖
I have submitted the modified version 0.3.4 to the web store for review!

**Comment by lheydon** [comment]
> I have submitted the modified version 0.3.4 to the web store for review!

Awesome, yes it is fixed now with **0.3.4** 👍

**どうもありがとう** (many thanks)
