### ISSUE TITLE
<>

### ISSUE THREAD

**Issue by hypenage** [yakisova41/return-youtube-comment-username#45]
The userscript makes channels that have angled brackets in their name like **\<name\>** have no name. (Firefox)
### Images:
- [rycu disabled](https://files.catbox.moe/oi9l8m.png)
- [rycu enabled](https://files.catbox.moe/1nmhqo.png) [The name is supposed to say \<\/xii\> but it shows nothing]
- [the video this comment was on](https://www.youtube.com/watch?v=8kAG2LYOSj8&lc=Ugx2ZNwF_fZytaWFJwZ4AaABAg)

**Comment by yakisova41** [comment]
Can you please provide the URL of the video where the problem occurs?

**Comment by yakisova41** [comment]
Fixed in v0.3.6!!!!
