### ISSUE TITLE
My username being replaced with someone else's username!

### ISSUE THREAD

**Issue by lheydon** [yakisova41/return-youtube-comment-username#46]
Ok, this is a weird one. Script was working fine. I typed and submitted a response on a comment thread. The submitted comment showed the username _'[redacted]'_ rather than my own username (or my own handle which would be expected if the script had somehow stopped working or needed the content manually refreshed before it could replace my handle with my user name).

Reloaded the page and everything was fixed and working fine again.

The username _'[redacted]'_ has no connection whatsoever to my own username or handle, nor any existing username or handle, nor to any piece of data conceivably linked to anything on my YouTube profile/channel/account.
Interesting what you think about this one.

P.S. Am using VPN/adblocker/script blocker. Neither of the latter two should affect scripts running client-side via a plugin though, should they? Only server-side scripts?

**_EDIT: Corrected incorrect statement._**

**Comment by lheydon** [comment]
P.S. OK, it just happened again while reloading the same page and looking at the same existing comment that had the issue previously. This time it was a different username substituted in, and this time **was** one that belonged to someone who comments on that channel.

Fixed again instantly with another reload.

P.S. Am using VPN/adblocker/script blocker. Neither of the latter two should affect scripts running client-side via a plugin though, should they? Only server-side scripts?

**Comment by yakisova41** [comment]
In summary, does that mean that another person's name appears in the reply?
Translation sites don't seem to be good with long sentences. 😥

**Comment by lheydon** [comment]
> In summary, does that mean that another person's name appears in the reply?
> Translation sites don't seem to be good with long sentences. 😥

That's a real shame, because people who know me would confirm that long sentences are kind of my default setting 😂

No, the other person's name doesn't 'appear' in the reply, at least not in the permanent sense. It's simply displayed in place of my own name, until a refresh is done and my correct name then returns. Although a subsequent refresh did then display a different incorrect name. Which again went away with a refresh.

Does that clarify better?

**Comment by lheydon** [comment]
P.S. Oh, on browsing one of the sub-threads, I just noticed that **both** incorrect usernames did actually belong to other people in that comment section. So at least the script is incorrectly displaying names that were definitely sourced from the page, rather than just out of thing air 😀

**Comment by lheydon** [comment]
P.P.S. Oh and I've also screen captured another time when it happened just now. With a whole bunch of different people's usernames all incorrectly replaced. Including my own username incorrectly replaced with different incorrect usernames across different comments. All of the usernames presumably belonging to other real people who commented somewhere on the same comment section. It fixed itself after a reload. And I have both before and after screenshots.

But it's semi-private so I'll need to e-mail it to you directly, if you can provide me with your e-mail address?

**Comment by yakisova41** [comment]
I submitted version 0.3.6 for review, which has improved the process around replies, but I'm not sure if it has been fixed. I'm not sure if it's fixed 😖.
If it is not fixed, please capture it to `yakisoba5emon@gmail.com`😊.

**Comment by lheydon** [comment]
Sure, I'll update my version and let you know if the problem continues. Thanks!

**Comment by lheydon** [comment]
Just discovered issue is still persisting with **0.3.6**. Will e-mail you screenshots soon.

**Comment by yakisova41** [comment]
I was able to reproduce probably the same bug in version 0.3.6.
I tried the same procedure with version 0.3.7, which was pre-released on github and greasyfork, and somehow that bug was fixed.
I'm not sure, but anyway, I've released 0.3.7 to the chrome web store as well, so could you please check if the bug occurs?

**Comment by lheydon** [comment]
Sure will upgrade and give it a try and let you know if it persists or not.

**Comment by lheydon** [comment]
**@yakisova41**, sorry just realised I never responded here. The issue was seen again once or twice and now seems to have resolved itself.

**Comment by lheydon** [comment]
@yakisova41, this issue has also started happening again in certain contexts. I will e-mail you screenshots directly.
