### ISSUE TITLE
Would it be possible to display username and handle at the same time?

### ISSUE THREAD

**Issue by klobouki** [yakisova41/return-youtube-comment-username#51]
Would it be possible to display username and handle at the same time? I think it would be very beneficial. Thank you.

**Comment by yakisova41** [comment]
Sorry, but this is only a "return to original" extension, so it will not add any more functionality than the original.
This extension is MIT licensed, so you are free to use the code as long as you credit `Copyright (c) 2022 yakisova41`. How about making your own?
