### ISSUE TITLE
Adding a tooltip showing the handle underneath the replaced username?

### ISSUE THREAD

**Issue by lheydon** [yakisova41/return-youtube-comment-username#54]
Not sure if this is even possible to implement or not. Would it be possible when hovering the mouse over the (replaced) username, to have a pop-up tooltip show what the handle underneath is?

![restore-youtube-usernames-tooltip-feature-idea](https://github.com/yakisova41/return-youtube-comment-username/assets/137272414/7028777c-4307-4991-b163-b9d2680c5541)

Currently, while your extension is great for restoring the username, if someone makes written reference (as in not tagged or linked and therefore not replaceable) to a handle, then it can be difficult to tell who they are referring to if the username is significantly different from the handle. Currently, you need to visit the profiles of all of the commenters to see what their handles are and work out who is being referred to.

I'm not sure whether the tooltip level can even be customised with extensions or not, or whether it is too fundamental of a base component of Chrome.

Hope this makes sense, and the mock-up image helps.

**Comment by yakisova41** [comment]
Technically possible
but not possible because it slows down processing when performing a large number of DOM operations.😥

**Comment by lheydon** [comment]
Oh OK, that's a shame but thanks for considering it.
