### ISSUE TITLE
[Bug]: Extension does not work anymore today, Handles now everywhere again

### ISSUE THREAD

**Issue by mrkrabs206** [yakisova41/return-youtube-comment-username#55]
### Browser

Chrome 114.0.5735.199

### Release Type

Chrome Extension

### The URL where the problem occurred

https://www.youtube.com/watch?v=x-6RNvEibRw

### What scripts or extensions do you use with it?

Return YouTube Dislike

Youtube-shorts block

No YouTube Shorts

YouTube channel location

### What is the problem?

Hi, I was using your extension for over a month. Now suddenly, it's not working anymore. I'm not sure what just happened,
seems like it just now shows Handles (@username) again instead of the normal ones (Username).
Was it me, or just YouTube messed this up so much?
I also removed and added this extension again, nothing changed.
I'm using latest version (0.3.7). Right now, I have uninstalled the extension to give me a fix for this problem.
Thanks-! @yakisova41

**Comment by yakisova41** [comment]
It is working fine in my environment, but seems to be buggy in some users' environments.
I would like to know about some of the bugs.

## Has there been any recent updates that significantly change the YouTube UI?
Only some users may be provided with updates to the YouTube client ahead of time.
For your information, the client version that is working properly in my environment is `youtube.player.web_20230718_01_RC00`.
You can get this from the "Copy debug info" that appears when you right-click on a video.

## Are you getting videos.xml?
Starting with version 0.3.7, we have changed to use an API that uses videos.xml.
This change may cause problems for some users.
When you open the Network tab of DevTools, which you can open with the `F12` key, and scroll down to the comments, if videos.xml is read without error, you can confirm that the API is OK (it will be
![スクリーンショット 2023-07-21 151135](https://github.com/yakisova41/return-youtube-comment-username/assets/75610521/46e6f991-987c-4e21-a761-56dc0305e6f1)
 in red when there is an error.)

## Are there any error logs other than TrustedHTML, Script?
Is the error log displayed in the DevTools Console?

**Comment by Nocretsis** [comment]
I think i found there is a crash while using adblock at the same time.

while i use [this](https://chrome.google.com/webstore/detail/adblock-%E2%80%94-best-ad-blocker/gighmmpiobklfepjocnamgkkbiglidom) adblock extension, your extension become malfunction.

DevTools Console show error like this
```
Uncaught TypeError: Cannot convert undefined or null to object
    at hasOwnProperty (<anonymous>)
    at ke (embed.js:1:338)
    at qe (embed.js:1:466)
    at embed.js:7:4471
ke @ embed.js:1
qe @ embed.js:1
(anonymous) @ embed.js:7
```

**Comment by mrkrabs206** [comment]
I don't see these errors. **videos.xml** is missing, and AdBlockPlus doesn't show this error about that. I even turned off both Bitdefender Anti-tracker and AdBlockPlus, nothing happened as well.
Give me another solution to these problems related.
![no error about this extension](https://github.com/yakisova41/return-youtube-comment-username/assets/110676833/a457c210-5c8e-44e7-8183-250953401952)
![handle still shown i hate this](https://github.com/yakisova41/return-youtube-comment-username/assets/110676833/9e8d8081-8747-41f5-94d4-80cad6b0bd32)

**Comment by yakisova41** [comment]
Since the external library fast-xml-parser may not be working because of it, we have created a version without it.
If you would like, could you please try the beta version in the zip below?
[rycu0.3.8-beta.zip](https://github.com/yakisova41/return-youtube-comment-username/files/12136634/rycu0.3.8-beta.zip)

**Comment by mrkrabs206** [comment]
Nope, that didn't help.

**Comment by mrkrabs206** [comment]
Nothing was changed. Agggggh!!!!

**Comment by yakisova41** [comment]
🤨
Do you have rycu logs in console like this?
![スクリーンショット 2023-07-23 020942](https://github.com/yakisova41/return-youtube-comment-username/assets/75610521/72389201-ab10-4b25-a6b9-b498db175683)

**Comment by FozuBlessNoBug** [comment]
same problem

**Comment by mrkrabs206** [comment]
No, just these errors from the extension itself. OH. MY. GOD!!!!!!!
![extension errors](https://github.com/yakisova41/return-youtube-comment-username/assets/110676833/a4e22e24-c492-4bbf-a6a6-fc3056f6e34b)

**Comment by mrkrabs206** [comment]
> same problem

right bro. 😞

**Comment by yakisova41** [comment]
> No, just these errors from the extension itself. OH. MY. GOD!!!!!!! ![extension errors](https://user-images.githubusercontent.com/110676833/255428715-a4e22e24-c492-4bbf-a6a6-fc3056f6e34b.PNG)

Don't worry about that error, it's not a big deal 😁.

If you are seeing that error, it means that at least the script is working, so you should see videos.xml in the Network tab as well.

Nonetheless the name is not rewritten?
Or has it improved?

**Comment by mrkrabs206** [comment]
> > No, just these errors from the extension itself. OH. MY. GOD!!!!!!! ![extension errors](https://user-images.githubusercontent.com/110676833/255428715-a4e22e24-c492-4bbf-a6a6-fc3056f6e34b.PNG)
> 
> Don't worry about that error, it's not a big deal 😁.
> 
> If you are seeing that error, it means that at least the script is working, so you should see videos.xml in the Network tab as well.
> 
> Nonetheless the name is not rewritten? Or has it improved?

Still no videos.xml and the name is not rewritten either.

**Comment by mrkrabs206** [comment]
Not improved.

**Comment by yakisova41** [comment]
Seriously, I can't figure out the cause🤨🤨
so I created a version with more detailed logs and a few fixes.
[rycu0.3.8-debug.zip](https://github.com/yakisova41/return-youtube-comment-username/files/12139948/rycu0.3.8-debug.zip)

https://www.youtube.com/watch?v=x-6RNvEibRw
Can you please copy and paste all the logs when you access

**Comment by mrkrabs206** [comment]
> Seriously, I can't figure out the cause🤨🤨 so I created a version with more detailed logs and a few fixes. [rycu0.3.8-debug.zip](https://github.com/yakisova41/return-youtube-comment-username/files/12139948/rycu0.3.8-debug.zip)
> 
> https://www.youtube.com/watch?v=x-6RNvEibRw Can you please copy and paste all the logs when you access

Did not work either, same thing. Even reloaded the unpacked extension and the YouTube video page many times. No results.
That's it. I will close this as **Not planned** . See for yourself @yakisova41 and @FozuBlessNoBug . Update officialy in the Web Store and change description for the new update. Goodbye.
![extension is broken](https://github.com/yakisova41/return-youtube-comment-username/assets/110676833/d3639ff1-a163-41d6-a40c-8851f0354574)
![broken extension](https://github.com/yakisova41/return-youtube-comment-username/assets/110676833/ad357ff8-a2b4-42df-9500-9d7608ce6f2f)

**Comment by mrkrabs206** [comment]
Thankfully, I have found another extension/script from Greasy Fork (which is a Tampermonkey script). Done. Case closed! This extension will be fixed soon. @yakisova41

**Comment by mrkrabs206** [comment]
Thankfully, I have found another extension/script from Greasy Fork (which is a Tampermonkey script). Done. Case closed! This extension will be fixed soon. @yakisova41

**Comment by mrkrabs206** [comment]
Except when another video is open, then these handles are shown. So always refresh them.

**Comment by yakisova41** [comment]
> Seriously, I can't figure out the cause🤨🤨
> 
> so I created a version with more detailed logs and a few fixes.
> 
> [rycu0.3.8-debug.zip](https://github.com/yakisova41/return-youtube-comment-username/files/12139948/rycu0.3.8-debug.zip)
> 
> 
> 
> https://www.youtube.com/watch?v=x-6RNvEibRw
> 
> Can you please copy and paste all the logs when you access
> 
> 

This version is just for debugging with added logs, so it's not surprising that it doesn't improve 😅.
I wanted to know where you got stuck by looking at the logs, but if you are going to use a derivation of my script then that's it 🤓.

If you are not willing to help me fix the bug, please refrain from making future issues 😉.

Goodbye 👋👋
