### ISSUE TITLE
[Bug]: Extension doesn't work

### ISSUE THREAD

**Issue by TylerWDoesStuff** [yakisova41/return-youtube-comment-username#61]
### Browser

Microsoft Edge 115.0.1901.188 (Official build) (64-bit)

### Version

0.3.8 debug (see below)

### YouTube Client Version

youtube.player.web_20230806_00_RC00

### Release Type

Chrome Extension

### The URL where the problem occurred

https://www.youtube.com/watch?v=5OllEcnsAUQ

### What scripts or extensions do you use with it?

AdNauseum (disabled)
Return YouTube Dislike
Bitwarden
ChatReplay
Fakespot
+ some others that I'm fairly sure don't affect YouTube / are only enabled when clicked on

### What is the problem?

Extension continuously shows the handle rather than usernames. I've used [this debug build from another issue](https://github.com/yakisova41/return-youtube-comment-username/issues/55#issuecomment-1646957892) and it seems to continue to loop find channel IDs.

The console's flooded with queries similar to below. I originally installed 0.3.9, but it behaves the same as this debug build.
![image](https://github.com/yakisova41/return-youtube-comment-username/assets/70175654/4b1ee990-f2aa-4ffe-b760-ce780ebee169)

I'm assuming it's trying to get channel usernames for these comments, though I'm not sure.
![image](https://github.com/yakisova41/return-youtube-comment-username/assets/70175654/eff609c3-f321-4fc7-ad53-e7fea5e43f42)

**Comment by TylerWDoesStuff** [comment]
Forgot to mention, but no video.xml files or anything similar.

**Comment by TylerWDoesStuff** [comment]
I just tried installing the userscript, and it didn't help.
However, I remembered that there were a few errors when loading, so I've attached them below.

![image](https://github.com/yakisova41/return-youtube-comment-username/assets/70175654/c3ecd2fa-b3f5-4152-8019-96057233b770)

**Comment by lheydon** [comment]
**@yakisova41**, yes the Chrome extension has also suddenly stopped working for me within the past day or two (version **0.3.9**). I haven't tried the script version.

The usernames are **not** correctly replaced with handles in the following places:
- Comment sections
- Detailed section of the notification drop-down.

However, for some reason they **are** still replaced correctly in the overview version of the notification drop-down.

See attached images below.

<hr>

- **_Not working in comment sections:_**

![fault3](https://github.com/yakisova41/return-youtube-comment-username/assets/137272414/c6ae1400-87fa-4c2b-90d4-5b7a45c9cf9f)

<hr>

- **_Not working in detailed section of the notification drop-down:_**

![fault1](https://github.com/yakisova41/return-youtube-comment-username/assets/137272414/4e0469cc-7f19-466d-8368-5ca56f774066)

<hr>

- **_Is still working in the overview version of the notification drop-down:_**

![fault2](https://github.com/yakisova41/return-youtube-comment-username/assets/137272414/bacfcd55-0b82-4d54-bb5d-15c02b9116d5)

Thanks in advance!

**Comment by lheydon** [comment]
**@yakisova41**,

> I've created a beta version, could you please try it?

Sure, I can try it if you explain how to install it. Is that beta a Chrome extension, or a userscript? I'm thinking the latter? I'm currently only using the Chrome extension, but can install one of the Monkey extensions to run the script.

**Comment by yakisova41** [comment]
> **@yakisova41**,
> 
> > I've created a beta version, could you please try it?
> 
> Sure, I can try it if you explain how to install it. Is that beta a Chrome extension, or a userscript? I'm thinking the latter? I'm currently only using the Chrome extension, but can install one of the Monkey extensions to run the script.

This is a chrome extension
From the extension's screen, go to developer mode and load the unzipped folder from "Load unpacked".
https://developer.chrome.com/docs/extensions/mv3/getstarted/development-basics/#load-unpacked

**Comment by lheydon** [comment]
Installed beta **0.3.10** and disabled previous version **0.3.9**.

Outcomes as follows:

<hr>

- Works in brief notifications dropdown.
 
![fault7](https://github.com/yakisova41/return-youtube-comment-username/assets/137272414/5eaf2114-079c-42e6-8c7f-cd9f12fdb01c)

<hr>

- Works in detailed notifications dropdown.
 
![fault4](https://github.com/yakisova41/return-youtube-comment-username/assets/137272414/a3d9fb24-ff56-42ab-afc4-a583ea2ce1f2)

<hr>

- Works in a fully expanded comment section thread.
 
![fault5](https://github.com/yakisova41/return-youtube-comment-username/assets/137272414/4f1d471e-254a-49ba-b27e-e28173b0cd7a)

<hr>

- When it is the 'highlighted reply', does **not** work when the comment thread has not been fully expanded.
 
![fault6](https://github.com/yakisova41/return-youtube-comment-username/assets/137272414/dea754af-4426-44de-b314-62de0150cb55)

**Comment by yakisova41** [comment]
Perhaps this version will fix all the problems.
If there are no problems, we will release it. Could you please confirm this?
[rycu-0.3.10-beta2.zip](https://github.com/yakisova41/return-youtube-comment-username/files/12292536/rycu-0.3.10-beta2.zip)

**Comment by lheydon** [comment]
**@yakisova41**, yes I just tested **0.3.10-beta2** and it fixes all of the problems 👍

Many thanks.

**Comment by TylerWDoesStuff** [comment]
Beta 2 works for me as well!
Thank you!
