### ISSUE TITLE
Another issue with 0.3.10.2 beta (punctuation displaying as HTML entity codes)

### ISSUE THREAD

**Issue by lheydon** [yakisova41/return-youtube-comment-username#65]
ATTN: @yakisova41 

Version is: **0.3.10.2 beta**

Problem is: The punctuation in replaced usernames is not displaying correctly, it displays as the HTML entity code instead in certain places (but not everywhere, see examples below).

Example: Apostrophe (**'**) incorrectly displayed as **`&#39;`**

Screenshots:

_Working correctly highlighted in **GREEN**.
Not working correctly highlighted in **RED**._

<hr>

- **Notification drop-down (overview):**

![notifications-normal](https://github.com/yakisova41/return-youtube-comment-username/assets/137272414/854c6f92-4950-4273-96b3-0eebabb7be7f)

<hr>

- **Notification drop-down (expanding specific comment):**

![notifications-expanded](https://github.com/yakisova41/return-youtube-comment-username/assets/137272414/3b752412-15f1-4fd5-a193-6ba50682f481)

<hr>

- **Comment section (not expanded):**

![comment-section-normal](https://github.com/yakisova41/return-youtube-comment-username/assets/137272414/c906e976-737a-453a-b3a1-2cbad255bc8c)

<hr>

- **Comment section (expanded):**

![comment-section-expanded](https://github.com/yakisova41/return-youtube-comment-username/assets/137272414/a7183a2f-6ca3-4966-9084-d4f0016bbf30)

<hr>

**Comment by yakisova41** [comment]
Fixed in v0.3.11

**Comment by lheydon** [comment]
**@yakisova41**, this same issue has just returned (version **0.3.11**)

**Comment by lheydon** [comment]
**@yakisova41**, just FYI the punctuation problem has returned (version **0.3.12**).

**Note:** This example is for a username/comment I'm **not** receiving notifications for, so I only have screenshots of it happening within a comment section itself, and then compared to how the username appears on that person's profile itself.

<hr>

![fault1](https://github.com/yakisova41/return-youtube-comment-username/assets/137272414/bd56f96b-9cbf-4b5d-a063-c433fb67e8ba)

<hr>

![fault2](https://github.com/yakisova41/return-youtube-comment-username/assets/137272414/cf181780-6bdf-49d4-887c-9ab5b95af041)

<hr>
