### ISSUE TITLE
Entire add-on stopped working again

### ISSUE THREAD

**Issue by lheydon** [yakisova41/return-youtube-comment-username#68]
@yakisova41 ,

Further to just the punctuation issue returning yesterday (see https://github.com/yakisova41/return-youtube-comment-username/issues/65#issuecomment-1686234349), as of today the entire add-on (**0.3.11**) has stopped replacing handles with usernames completely in the following places (**RED** is not working, **GREEN** is working):

<hr>

- Comment notification drop down expanded view.

![issue 2](https://github.com/yakisova41/return-youtube-comment-username/assets/137272414/c50ee844-8b33-4031-8ec7-9bfeb7f50985)

<hr>

- Comment section as highlighted response, section not expanded.

![issue 4](https://github.com/yakisova41/return-youtube-comment-username/assets/137272414/9af01137-6a73-4fb6-9acd-8568c37f66fb)

<hr>

- Comment section expanded.

![issue 1](https://github.com/yakisova41/return-youtube-comment-username/assets/137272414/47e73a4b-9cd7-425b-8f4d-5c9a74a8a6f2)

<hr>

However, it still works here:

<hr>

- Comment notification drop down overview.

![issue 3](https://github.com/yakisova41/return-youtube-comment-username/assets/137272414/90a06d92-22e1-4406-8474-d4a9c7b005db)

<hr>

**Comment by yakisova41** [comment]
There was a small spec change on YouTube 😡.
Will be fixed soon.

**Comment by lheydon** [comment]
> In which video did you encounter punctuation problems in your comments?
> Can you send me the URL?

**@yakisova41,** I've just e-mailed you the video URL directly.

Thanks.

**Comment by yakisova41** [comment]
We have created a beta version that fixes the problem.
Could you please let me know if it has been fixed?
[rycu0.3.12-beta2.zip](https://github.com/yakisova41/return-youtube-comment-username/files/12405508/rycu0.3.12-beta2.zip)

**Comment by yakisova41** [comment]
The corrected version 0.3.12 has been submitted for review.
Please wait for a while for its release.

**Comment by lheydon** [comment]
> The corrected version 0.3.12 has been submitted for review.
> Please wait for a while for its release.

**@yakisova41**, I just downloaded and installed the **0.3.12-beta2** you posted and it fixes all of the problems. Assuming this will also be the case with the corrected version **0.3.12** once released.

Have you considered charging a small amount for this add-on, or perhaps seeking optional donations? YouTube's constant changes mean you are updating it fairly often, and I for one would be happy to contribute a small amount to help reimburse for your time and effort in fixing what is a constant and major inconvenience for most YouTube commenters, and which YouTube themselves don't care about changing despite heaps of negative user feedback.
