### ISSUE TITLE
[Bug]: Children Cannot Get by Index

### ISSUE THREAD

**Issue by jan-ale** [yakisova41/return-youtube-comment-username#74]
### Browser

Chrome

### Version

I have no idea

### YouTube Client Version

youtube.player.web_20231001_00_RC01

### Release Type

Chrome Extension

### The URL where the problem occurred

https://www.youtube.com/watch?v=dQw4w9WgXcQ

### What scripts or extensions do you use with it?

disabled everything, still errors

### What is the problem?

Return YouTube Comment Username Warning Children Cannot Get by Index!
id of element attempting to retrieve: body/comment (both)
If you find this debug log, please report it to the github issue
still works, but the console is filled with these messages

**Comment by yakisova41** [comment]
Fixed in v0.3.14!
