### ISSUE TITLE
Stopped working again

### ISSUE THREAD

**Issue by lheydon** [yakisova41/return-youtube-comment-username#77]
@yakisova41, the extension has stopped working again in most places (**0.3.14**).

Notifications dropdown summary: Working

Notifications dropdown expanded: Not working.

Comment section normal: Not working.

Comment section expanded: Not working.

I will e-mail you screenshots directly.

Thanks in advance.

LH

**Comment by lheydon** [comment]
@yakisova41, OK so is version **0.3.15** being pushed through as a Chrome update?

**Comment by yakisova41** [comment]
> @yakisova41, OK so is version **0.3.15** being pushed through as a Chrome update?

Will be released as soon as the chrome web store review is complete
