### ISSUE TITLE
Not working again

### ISSUE THREAD

**Issue by lheydon** [yakisova41/return-youtube-comment-username#80]
**@yakisova41** , the extension has stopped working again in most places (**0.3.15**).

Notifications dropdown summary: Working

Notifications dropdown expanded: Not working.

Comment section normal: Not working.

Comment section expanded: Not working.

**Comment by yakisova41** [comment]
Fiexed in v0.3.16
please try update

**Comment by lheydon** [comment]
@yakisova41, many thanks. Confirmed update **v0.3.16** fixed everything 👍
