### ISSUE TITLE
Stopped working again (0.4.1)

### ISSUE THREAD

**Issue by lheydon** [yakisova41/return-youtube-comment-username#87]
**@yakisova41**, the extension has stopped working again in most places (**0.4.1**).

Notifications dropdown summary: Working

Notifications dropdown expanded: Not working.

Comment section normal: Not working.

Comment section expanded: Not working.

Thanks in advance!

**Comment by yakisova41** [comment]
YouTube is currently A/B testing a new friggin' UI.
I will fix when the new UI is implemented on my account.

**Comment by lheydon** [comment]
**@yakisova41**, OK many thanks! 👍

**Comment by VovaBob87** [comment]
Hi, what's the problem?

![Screenshot_472](https://github.com/yakisova41/return-youtube-comment-username/assets/162270951/d74b2ffd-968f-445a-a137-c278b781397d)

**Comment by lheydon** [comment]
@VovaBob87, this should probably be posted as a new issue rather than a comment on an existing, separate issue.

**Comment by DarkEXE** [comment]
> @yakisova41 Hi, what's the problem?
> 
> ![Screenshot_472](https://private-user-images.githubusercontent.com/162270951/309981350-d74b2ffd-968f-445a-a137-c278b781397d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2ODQ1ODAsIm5iZiI6MTcwOTY4NDI4MCwicGF0aCI6Ii8xNjIyNzA5NTEvMzA5OTgxMzUwLWQ3NGIyZmZkLTk2OGYtNDQ1YS1hMTM3LWMyNzhiNzgxMzk3ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNlQwMDE4MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MGM1MGE2YWZiNjFkYzEwODQwNTY1ZjJjYWIyZGQ3YTFjYjY5NDg4MjRlZDk3OTM3NzJkZDI1YTAwMTVkNjQ3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.nqbOcK8R-1VV1qRcDePgsU-ph0Bk5MZiI8A5epLPMOc)

I have the same problem.

**Comment by yakisova41** [comment]
> @yakisova41 Hi, what's the problem?
> 
> ![Screenshot_472](https://private-user-images.githubusercontent.com/162270951/309981350-d74b2ffd-968f-445a-a137-c278b781397d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3MjkwMjcsIm5iZiI6MTcwOTcyODcyNywicGF0aCI6Ii8xNjIyNzA5NTEvMzA5OTgxMzUwLWQ3NGIyZmZkLTk2OGYtNDQ1YS1hMTM3LWMyNzhiNzgxMzk3ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNlQxMjM4NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMDA4MGJlMTQ1NDRkMWY2ZDJjN2JmNmIyNDUyYzMzMWU3YTJjYjBlM2M4MWUxZjdhZTQyMWQ2YjBlMDhjODYxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.y9C2KcANR9EGIdxVete0NPRGssVzkbxSvk8eWBt1YV4)

Can you show me a screenshot or a copy of the console that appears with F12? @DarkEXE @VovaBob87

**Comment by DarkEXE** [comment]
> > @yakisova41 Hi, what's the problem?
> > ![Screenshot_472](https://private-user-images.githubusercontent.com/162270951/309981350-d74b2ffd-968f-445a-a137-c278b781397d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3MjkwMjcsIm5iZiI6MTcwOTcyODcyNywicGF0aCI6Ii8xNjIyNzA5NTEvMzA5OTgxMzUwLWQ3NGIyZmZkLTk2OGYtNDQ1YS1hMTM3LWMyNzhiNzgxMzk3ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNlQxMjM4NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMDA4MGJlMTQ1NDRkMWY2ZDJjN2JmNmIyNDUyYzMzMWU3YTJjYjBlM2M4MWUxZjdhZTQyMWQ2YjBlMDhjODYxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.y9C2KcANR9EGIdxVete0NPRGssVzkbxSvk8eWBt1YV4)
> 
> Can you show me a screenshot or a copy of the console that appears with F12? @DarkEXE @VovaBob87

![image](https://github.com/yakisova41/return-youtube-comment-username/assets/44385558/9f9d5ab3-6eb0-41e5-9ead-8a156f227548)

**Comment by VovaBob87** [comment]
> Published version 0.4.2 with (possibly) bug fixes. The chrome extension will be released within about 3 days. The userscript can be updated now.

It works again. Thanks, my friend!
![Screenshot_475](https://github.com/yakisova41/return-youtube-comment-username/assets/162270951/a566fb10-d23d-43ea-9088-edae6fd8b5e9)

**Comment by lheydon** [comment]
> Published version 0.4.2 with (possibly) bug fixes. The chrome extension will be released within about 3 days. The userscript can be updated now.

Upgraded and all aspects working fine again now, many thanks @**yakisova41**! 👍
