### ISSUE TITLE
Stopped working again (0.4.2)

### ISSUE THREAD

**Issue by lheydon** [yakisova41/return-youtube-comment-username#91]
**@yakisova41**, the extension has just stopped working again in some places (0.4.2).

Notifications dropdown summary: Working

Notifications dropdown expanded: Not working.

Comment section normal: Not working.

Comment section expanded: Working.

Thanks in advance!

**Comment by yakisova41** [comment]
Are there displayed any errors in console? would you paste a screenshot please?
@lheydon 
Thenks.

**Comment by lheydon** [comment]
> Are there displayed any errors in console? would you paste a screenshot of console please? @lheydon Thenks.

Sure @yakisova41 I can check, do you mean the standard console as in the 'Chrome menu ➔ Developer tools ➔ Console'? Or is there a different one specific to add-ons?

Is there a particular state you require YouTube to be in when I'm doing doing so, or just in any of the aforementioned states when the add-on isn't changing the handles to usernames correctly?

What am I specifically looking for in the console? Am I filtering it by a relevant keyword, such as '**_rycu_**'?

Thanks in advance 👍

**Comment by yakisova41** [comment]
You can open the console how press the F12 key in the page of problem.
Im looking for debug info by rycu (The line wrote INNERTUBE_CLIENT_VERSION at the top of the example screenshot) and any error.

Errors originating from rycu can be filtered by using the "rycu" keyword, but if there are other errors, they may be the cause of the error and therefore do not need to be filtered.

## Example 
![スクリーンショット 2024-03-30 233127](https://github.com/yakisova41/return-youtube-comment-username/assets/75610521/eab9fdb4-61ef-495b-a6fd-525a13cc0b5e)

**Comment by lheydon** [comment]
**@yakisova41**, this is filtered by '**_rycu_**'. Let me know if you want it unfiltered.

![Screenshot 2024-03-31 194640](https://github.com/yakisova41/return-youtube-comment-username/assets/137272414/895b5e62-7662-4aae-9b4e-ccd5e5c0081a)

**Comment by yakisova41** [comment]
I was able to confirm the issue of replies to comments in notifications not being rewritten myself.
> Comment section normal: Not working.

 are you experiencing the same problem with the /watch page?
If so, can you show me all the logs (unfiltered) that you can see in F12?

**Comment by yakisova41** [comment]
At any rate, I have probably found the cause of the problem and have submitted v0.5.0, which fixes it, for review.

Please wait for a while for its release.

**Comment by lheydon** [comment]
> At any rate, I have probably found the cause of the problem and have submitted v0.5.0, which fixes it, for review.
> 
> Please wait for a while for its release.

**@yakisova41**, sorry for the delay in responding. Everything now appears fixed for me in **v0.5.0** 👍
