### ISSUE TITLE
[Bug]: 機能しなくなりました。

### ISSUE THREAD

**Issue by yujean9191** [yakisova41/return-youtube-comment-username#93]
### Browser

Brave

### Version

Brave  1.64.113 Chromium: 123.0.6312.86（Official Build） （64 ビット）

### YouTube Client Version

youtube.player.web_20240326_01_RC00

### Release Type

Chrome Extension

### The URL where the problem occurred

https://www.youtube.com/watch?v=mkLRyhOxI7U

### What is the problem?

急に拡張機能が機能しなくなりました。2024年4月2日午前10時現在
拡張機能の再インストールやCookieの消去を試しても改善しません。
Youtube側の仕様変更によるものなのでしょうか...?
コメント欄からどんな感じの人がコメントしているのか判断するのに重宝していたのでこの機能が使えなくなると困ります

**Comment by yakisova41** [comment]
修正したv0.5.0を審査に出しました。
リリースまでしばらくお待ち下さい。

**Comment by yujean9191** [comment]
修正ありがとうございます。
なのですが、直接Githubからファイルを落として試してみたら問題が発生しているようなので新しいissueを見てもらえますでしょうか？？
