### ISSUE TITLE
[Bug]: It doesn't work

### ISSUE THREAD

**Issue by wiful10** [yakisova41/return-youtube-comment-username#94]
### Browser

chrome 123.0.6312.86

### Version

0.4.2

### YouTube Client Version

youtube.player.web_20240331_00_RC00

### Release Type

Chrome Extension

### The URL where the problem occurred

https://www.youtube.com/watch?v=djV11Xbc914

### What scripts or extensions do you use with it?

Return YouTube Comment Username chrome extension

### What is the problem?

![캡처](https://github.com/yakisova41/return-youtube-comment-username/assets/102317996/8bfff259-32f5-4576-a6fa-892aeec7b319)

The comment user name is displayed again in @ format.

**Comment by yakisova41** [comment]
The fixed v0.5.0 has been submitted for review.
Please wait for a while for its release.

**Comment by wiful10** [comment]
Thank you always!
